{
  "bug_id": "api-get--1761191496931",
  "workflow_id": "api-get-",
  "category": "api_endpoint_error",
  "priority": 65,
  "evidence": {
    "workflow_id": "api-get-",
    "started_at": "2025-10-23T03:51:36.928Z",
    "steps": [],
    "requests": [],
    "responses": [],
    "failed_at": "2025-10-23T03:51:36.930Z",
    "duration_ms": 2,
    "error": "request to http://localhost:3002/ failed, reason: "
  },
  "discovered_at": "2025-10-23T05:46:27.406Z"
}