{
  "bug_id": "api-post-api-calculate-with-trace-1761191496921",
  "workflow_id": "api-post-api-calculate-with-trace",
  "category": "api_endpoint_error",
  "priority": 65,
  "evidence": {
    "workflow_id": "api-post-api-calculate-with-trace",
    "started_at": "2025-10-23T03:51:36.918Z",
    "steps": [],
    "requests": [],
    "responses": [],
    "failed_at": "2025-10-23T03:51:36.921Z",
    "duration_ms": 3,
    "error": "request to http://localhost:3002/api/calculate-with-trace failed, reason: "
  },
  "discovered_at": "2025-10-23T05:46:27.447Z"
}